"""Synthesize PAL generator-input JSONL files from adapted Meddies records.

PIX-4070 Phases 2.1, 2.2, 3.1 require upstream intermediate JSONL files:

  - Phase 2.1 input (selection):  {dialogue, personas, correct_index}
  - Phase 2.2 input (dialogue):   {persona, dialogue?, response}
  - Phase 3.1 input (DPO):        {persona, dialogue?, chosen_response, rejected_response}

The PAL paper specifies that ``dialogue``, ``response``, ``chosen_response``,
and ``rejected_response`` should be generated by an LLM seeded with the persona.
This module supports two modes:

  * **Rule-based** (default, no API key required): deterministic Vietnamese-string
    templates that produce structurally valid records with persona-aligned
    content. Good for smoke tests and CI.
  * **LLM-driven** (``--llm`` flag or passing ``llm_client=`` to ``run()``):
    persona-aware prompts are sent to an LLM (default: NVIDIA NIM
    ``openai/gpt-oss-120b``) to produce varied, natural dialogue and responses.
    Falls back to rule-based generation if the LLM returns an empty/error string.

The ``llm_client`` parameter accepts any callable with signature
``llm_client(prompt: str, system_prompt: str | None = None) -> str``.
The repo's ``ai.utils.common.llm_client.LLMClient`` satisfies this contract
and is wired automatically when ``--llm`` is set.

Outputs are written to a single directory so downstream generators can pick
them up directly.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any, Callable, Iterable

from meddies_adapter import adapt_record
from meddies_to_pal import format_persona

logger = logging.getLogger(__name__)

# Type alias for the LLM callable contract.
LlmCallable = Callable[..., str]


def _safe_json(obj: Any) -> Any:
    """JSON fallback for datetime / date objects in upstream Meddies records."""
    if isinstance(obj, datetime):
        return obj.isoformat()
    if isinstance(obj, date):
        return obj.isoformat()
    raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")


def _dumps(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, default=_safe_json)


# --------------------------------------------------------------------------- #
# Rule-based generators (fallback when no LLM client configured)
# --------------------------------------------------------------------------- #

_GREETING_TEMPLATES = [
    "Xin chào bác sĩ, tôi là {name}, tôi {age} tuổi.",
    "Chào bác sĩ, tôi sống ở {location}. Hôm nay tôi đến khám vì người nhà khuyên.",
    "Bác sĩ ơi, tôi bị {symptom} đã mấy ngày rồi, không biết sao nữa.",
    "Tôi hơi lo lắng về tình trạng sức khỏe của mình, con tôi bảo tôi đi khám.",
]

_FOLLOWUP_TEMPLATES = [
    "Dạ, triệu chứng này bắt đầu từ bao giờ?",
    "Nhà tôi có dùng thuốc Nam nên tôi chưa uống thuốc Tây.",
    "Tôi không hiểu thuốc này lắm, bác sĩ giải thích đơn giản giúp tôi được không?",
    "Tôi sợ đi viện tuyến trên, ở quê nhà xa lắm.",
]


def _first_symptom(record: dict[str, Any]) -> str:
    med = record.get("medical_history", {}) or {}
    presenting = med.get("presenting_symptoms")
    if isinstance(presenting, list) and presenting:
        first = presenting[0]
        if isinstance(first, dict):
            name = first.get("symptom_name")
            if isinstance(name, str) and name:
                return name
    chronic = med.get("chronic_conditions", [])
    if isinstance(chronic, list) and chronic:
        return str(chronic[0])
    return "mệt mỏi"


def _synthesize_dialogue_rule(record: dict[str, Any], rng: random.Random, n_turns: int = 3) -> str:
    """Produce a short deterministic dialogue string (rule-based proxy).

    Returns a single string with each turn on its own line (Patient/Doctor).
    """
    raw = record.get("_raw", record)
    demo = raw.get("demographics", {}) or {}
    name = demo.get("full_name", "bệnh nhân")
    age = demo.get("age", "unknown")
    location = demo.get("province") or demo.get("location") or "Vietnam"
    symptom = _first_symptom(raw)

    lines: list[str] = []
    g = rng.choice(_GREETING_TEMPLATES).format(
        name=name, age=age, location=location, symptom=symptom
    )
    lines.append(f"Patient: {g}")
    for _ in range(max(1, n_turns - 1)):
        follow = rng.choice(_FOLLOWUP_TEMPLATES)
        lines.append(f"Doctor: {follow}")
    lines.append(f"Patient: Triệu chứng {symptom} làm tôi không ngủ được.")
    return "\n".join(lines)


def _synthesize_chosen_response_rule(record: dict[str, Any]) -> str:
    """Produce a persona-aligned response (low/average/high literacy style)."""
    adapted = record  # Already adapted
    health = adapted.get("healthcare_behavior", {})
    literacy = health.get("health_literacy", "average")
    preference = health.get("preference", "standard medicine")

    if literacy == "low":
        return (
            f"Tôi đã hiểu rồi bác sĩ ơi. {preference} tôi thường dùng là theo thói quen gia đình, "
            "nên tôi sẽ thử xem sao. Cảm ơn bác sĩ giải thích cho tôi hiểu."
        )
    if literacy == "high":
        persona_str = format_persona(adapted)
        return (
            f"Based on my persona: {persona_str}. I will discuss the differential diagnosis with my family "
            "and follow up if symptoms persist. Thank you, doctor."
        )
    return (
        f"Bác sĩ nói rõ ràng, tôi sẽ chú ý hơn. Tôi thường {preference.lower()}, "
        "sẽ cân nhắc theo lời khuyên của bác sĩ."
    )


def _synthesize_rejected_response_rule(record: dict[str, Any]) -> str:
    """Produce a persona-violating response (high jargon, generic AI tone)."""
    return (
        "As an AI assistant, I recommend you seek immediate care at a tertiary academic medical center. "
        "Per clinical guidelines, your symptoms warrant expedited neuroimaging and a multi-disciplinary "
        "review. Please consult your physician without delay."
    )


# --------------------------------------------------------------------------- #
# LLM-driven generators (swap-in via llm_client; rule-based fallback)
# --------------------------------------------------------------------------- #

_DIALOGUE_SYSTEM = (
    "You are a clinical roleplay generator. Given a patient persona and a"
    " presenting symptom, write a short (3-5 turn) outpatient clinic dialogue"
    " between Patient and Doctor. The Patient speaks Vietnamese at first and"
    " may switch to English only if their health_literacy is high. The"
    " Patient's voice MUST reflect the persona: age, gender, province, health"
    " literacy level, and healthcare-seeking preference. The Doctor asks"
    " clarifying questions. Format: one turn per line as"
    " 'Patient: ...' or 'Doctor: ...'. Output only the dialogue, no preface,"
    " no JSON, no commentary."
)

_CHOSEN_SYSTEM = (
    "You are writing the patient's next response in a clinical dialogue. The"
    " patient's response MUST strictly adhere to their persona: match their"
    " health literacy (low literacy = plain words, everyday vocabulary, may"
    " code-switch Vietnamese; high literacy = informed, asks specific"
    " questions), honor their healthcare-seeking preference (traditional"
    " medicine / western medicine / mixed / immediate care / self-treatment /"
    " no prior care), and respect cultural context (Vietnamese rural or"
    " urban). Output only the single response, no role label, no JSON, no"
    " preface."
)

_REJECTED_SYSTEM = (
    "You are writing a persona-violating response for a Direct Preference"
    " Optimization contrast pair. The response MUST IGNORE the given persona:"
    " use generic AI-assistant tone, heavy medical jargon regardless of the"
    " patient's literacy level, recommend immediate tertiary academic care"
    " regardless of the patient's preference or cultural context, and"
    " reference clinical guidelines. This is the rejected / dispreferred"
    " response. Output only the single response, no role label, no JSON, no"
    " preface."
)


def _llm_dialogue(record: dict[str, Any], llm_client: LlmCallable, rng: random.Random) -> str:
    raw = record.get("_raw", record)
    persona = format_persona(record)
    symptom = _first_symptom(raw)
    prompt = (
        f"Patient persona: {persona}\n"
        f"Presenting symptom: {symptom}\n"
        f"Seed (do not reuse verbatim): {rng.randint(0, 10**9)}\n"
        f"Write the dialogue now."
    )
    out = llm_client(prompt, system_prompt=_DIALOGUE_SYSTEM)
    return out.strip() if out else _synthesize_dialogue_rule(record, rng)


def _llm_chosen(record: dict[str, Any], llm_client: LlmCallable, rng: random.Random) -> str:
    persona = format_persona(record)
    health = record.get("healthcare_behavior", {})
    literacy = health.get("health_literacy", "average")
    preference = health.get("preference", "standard medicine")
    prompt = (
        f"Patient persona: {persona}\n"
        f"Health literacy: {literacy}\n"
        f"Healthcare-seeking preference: {preference}\n"
        f"Seed (do not reuse verbatim): {rng.randint(0, 10**9)}\n"
        f"Write the patient's next response now."
    )
    out = llm_client(prompt, system_prompt=_CHOSEN_SYSTEM)
    return out.strip() if out else _synthesize_chosen_response_rule(record)


def _llm_rejected(record: dict[str, Any], llm_client: LlmCallable, rng: random.Random) -> str:
    persona = format_persona(record)
    prompt = (
        f"Patient persona (to IGNORE): {persona}\n"
        f"Seed (do not reuse verbatim): {rng.randint(0, 10**9)}\n"
        f"Write the persona-violating response now."
    )
    out = llm_client(prompt, system_prompt=_REJECTED_SYSTEM)
    return out.strip() if out else _synthesize_rejected_response_rule(record)


def _make_synthesizers(llm_client: LlmCallable | None):
    """Return (dialogue_fn, chosen_fn, rejected_fn) bound to the right backend."""
    if llm_client is None:
        return (
            _synthesize_dialogue_rule,
            _synthesize_chosen_response_rule,
            _synthesize_rejected_response_rule,
        )

    def dialogue_fn(record, rng, n_turns: int = 3):
        return _llm_dialogue(record, llm_client, rng)

    def chosen_fn(record):
        return _llm_chosen(record, llm_client, rng=random.Random(rng_seed_for(record, "chosen")))

    def rejected_fn(record):
        return _llm_rejected(record, llm_client, rng=random.Random(rng_seed_for(record, "rejected")))

    return dialogue_fn, chosen_fn, rejected_fn


def rng_seed_for(record: dict[str, Any], salt: str) -> int:
    """Derive a deterministic per-record seed for LLM prompt variety."""
    raw = record.get("_raw", record)
    demo = raw.get("demographics", {}) or {}
    name = str(demo.get("full_name") or demo.get("age") or "x")
    return abs(hash(f"{name}-{salt}")) % (10**9)


# --------------------------------------------------------------------------- #
# Pipeline builders
# --------------------------------------------------------------------------- #

@dataclass
class SampledPersonas:
    dialogue: str
    personas: list[dict[str, Any]]
    correct_index: int


def build_selection_input(
    adapted_records: list[dict[str, Any]],
    rng: random.Random,
    n_distractors: int = 3,
    dialogue_fn: Callable | None = None,
) -> Iterable[dict[str, Any]]:
    """Build Phase 2.1 input records: {dialogue, personas, correct_index}."""
    if len(adapted_records) < 2:
        raise ValueError("need >=2 records to sample correct + distractors")

    def sample_pool(correct_idx: int, exclude: set[int]) -> list[dict[str, Any]]:
        pool: list[dict[str, Any]] = []
        candidate_indices = [i for i in range(len(adapted_records)) if i not in exclude]
        rng.shuffle(candidate_indices)
        for i in candidate_indices[:n_distractors]:
            pool.append(adapted_records[i])
        return pool

    for i, record in enumerate(adapted_records):
        exclude = {i}
        distractors = sample_pool(i, exclude)
        while len(distractors) < n_distractors:
            distractors.append(adapted_records[rng.randrange(len(adapted_records))])
        correct_record = record
        combined = list(distractors)
        correct_index = rng.randrange(len(combined) + 1)
        combined.insert(correct_index, correct_record)
        if dialogue_fn is None:
            dialogue = _synthesize_dialogue_rule(record, rng)
        else:
            dialogue = dialogue_fn(record, rng)
        yield {
            "dialogue": dialogue,
            "personas": combined,
            "correct_index": correct_index,
        }


def build_dialogue_input(
    adapted_records: list[dict[str, Any]],
    rng: random.Random,
    chosen_fn: Callable | None = None,
    dialogue_fn: Callable | None = None,
) -> Iterable[dict[str, Any]]:
    """Build Phase 2.2 input records: {persona, dialogue?, response}.

    ``persona`` is the *adapted* record (fixture shape), so that downstream
    ``format_persona`` can read demographics.age/gender/location and
    healthcare_behavior.health_literacy/preference. The raw Meddies record
    stays available via ``_raw`` if the consumer wants extra context.
    """
    for record in adapted_records:
        response = chosen_fn(record) if chosen_fn else _synthesize_chosen_response_rule(record)
        if dialogue_fn is None:
            dialogue = _synthesize_dialogue_rule(record, rng, n_turns=2)
        else:
            dialogue = dialogue_fn(record, rng)
        yield {
            "persona": record,
            "dialogue": dialogue,
            "response": response,
        }


def build_dpo_input(
    adapted_records: list[dict[str, Any]],
    rng: random.Random,
    chosen_fn: Callable | None = None,
    rejected_fn: Callable | None = None,
    dialogue_fn: Callable | None = None,
) -> Iterable[dict[str, Any]]:
    """Build Phase 3.1 input records: {persona, dialogue?, chosen_response, rejected_response}."""
    for record in adapted_records:
        chosen = chosen_fn(record) if chosen_fn else _synthesize_chosen_response_rule(record)
        rejected = rejected_fn(record) if rejected_fn else _synthesize_rejected_response_rule(record)
        if dialogue_fn is None:
            dialogue = _synthesize_dialogue_rule(record, rng, n_turns=2)
        else:
            dialogue = dialogue_fn(record, rng)
        yield {
            "persona": record,
            "dialogue": dialogue,
            "chosen_response": chosen,
            "rejected_response": rejected,
        }


# --------------------------------------------------------------------------- #
# Top-level runner
# --------------------------------------------------------------------------- #

def run(
    out_dir: Path,
    n_records: int,
    seed: int = 7,
    hf_split: str = "train",
    llm_client: LlmCallable | None = None,
) -> dict[str, int]:
    """Fetch n_records from Meddies HF dataset, adapt, synthesize, write JSONLs.

    When ``llm_client`` is provided (anything implementing
    ``__call__(prompt: str, system_prompt: str | None = None) -> str``), the
    three synthesis calls (dialogue / chosen / rejected) route through it
    instead of the deterministic rule-based templates. Empty or falsy LLM
    return values fall back to the rule-based generators so a single failed
    call cannot corrupt the entire batch.
    """
    from datasets import load_dataset

    rng = random.Random(seed)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. Load N records from HF (use slice — non-streaming is much faster than
    #    streaming for parquet datasets because it avoids per-row HTTP range reads).
    slice_spec = f"{hf_split}[:{n_records}]"
    print(f"[phase0] loading {slice_spec} from Meddies/meddies-persona-vie")
    ds = load_dataset("Meddies/meddies-persona-vie", split=slice_spec)
    adapted_records: list[dict[str, Any]] = []
    for raw in ds:
        adapted_records.append(adapt_record(dict(raw)))

    print(f"[phase0] adapted {len(adapted_records)} records")

    # 2. Phase 1: format persona strings
    pal_phase1_path = out_dir / "pal_persona_strings.jsonl"
    with pal_phase1_path.open("w", encoding="utf-8") as f:
        for r in adapted_records:
            f.write(_dumps({"persona_string": format_persona(r)}) + "\n")
    print(f"[phase1] wrote {pal_phase1_path}")

    # 3. Build generator inputs (LLM-driven when llm_client provided)
    dialogue_fn, chosen_fn, rejected_fn = _make_synthesizers(llm_client)
    mode_label = "llm" if llm_client is not None else "rule-based"

    selection_path = out_dir / "input_phase_2_1_selection.jsonl"
    with selection_path.open("w", encoding="utf-8") as f:
        for rec in build_selection_input(adapted_records, rng, dialogue_fn=dialogue_fn):
            f.write(_dumps(rec) + "\n")
    print(f"[phase2.1-input] wrote {selection_path} ({mode_label})")

    dialogue_path = out_dir / "input_phase_2_2_dialogue.jsonl"
    with dialogue_path.open("w", encoding="utf-8") as f:
        for rec in build_dialogue_input(
            adapted_records, rng, chosen_fn=chosen_fn, dialogue_fn=dialogue_fn
        ):
            f.write(_dumps(rec) + "\n")
    print(f"[phase2.2-input] wrote {dialogue_path} ({mode_label})")

    dpo_path = out_dir / "input_phase_3_1_dpo.jsonl"
    with dpo_path.open("w", encoding="utf-8") as f:
        for rec in build_dpo_input(
            adapted_records,
            rng,
            chosen_fn=chosen_fn,
            rejected_fn=rejected_fn,
            dialogue_fn=dialogue_fn,
        ):
            f.write(_dumps(rec) + "\n")
    print(f"[phase3.1-input] wrote {dpo_path} ({mode_label})")

    return {
        "adapted": len(adapted_records),
        "mode": mode_label,
        "pal_phase1": pal_phase1_path.stat().st_size,
        "phase_2_1_input": selection_path.stat().st_size,
        "phase_2_2_input": dialogue_path.stat().st_size,
        "phase_3_1_input": dpo_path.stat().st_size,
    }


def _build_llm_client_from_env(model: str | None = None) -> LlmCallable | None:
    """Construct the repo's ``LLMClient`` against NIM using env vars.

    Honors ``NVIDIA_API_KEY`` / ``LLM_API_KEY`` / ``OPENAI_API_KEY``. Prefers
    the NVIDIA NIM base URL (``https://integrate.api.nvidia.com/v1``) unless
    ``LLM_BASE_URL`` is already set. Returns ``None`` when no key is present
    so the caller can fall back to rule-based generation.
    """
    api_key = (
        os.environ.get("NVIDIA_API_KEY")
        or os.environ.get("LLM_API_KEY")
        or os.environ.get("OPENAI_API_KEY")
    )
    if not api_key:
        logger.warning(
            "No NVIDIA_API_KEY / LLM_API_KEY found — falling back to rule-based synthesis."
        )
        return None

    # Bridge env so OpenAIDriver (which reads LLM_API_KEY/LLM_BASE_URL/LLM_MODEL)
    # lands on the NVIDIA NIM endpoint.
    os.environ.setdefault("LLM_API_KEY", api_key)
    os.environ.setdefault("LLM_BASE_URL", "https://integrate.api.nvidia.com/v1")
    if model:
        os.environ["LLM_MODEL"] = model
    else:
        os.environ.setdefault("LLM_MODEL", "openai/gpt-oss-120b")

    try:
        from ai.utils.common.llm_client import LLMClient
    except ImportError:
        # Synthesizer is invoked with PYTHONPATH=training_corpus/pal_framework.
        # Add the repo root so the import resolves.
        repo_root = str(Path(__file__).resolve().parents[3])
        sys.path.insert(0, repo_root)
        from ai.utils.common.llm_client import LLMClient  # type: ignore[import-not-found]

    client = LLMClient(driver="nvidia")
    logger.info(
        "LLMClient (driver=nvidia, model=%s, base_url=%s) wired for synthesis",
        getattr(client.driver, "model", "unknown"),
        getattr(client.driver, "base_url", "unknown"),
    )
    return client


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Synthesize PAL generator inputs from Meddies/meddies-persona-vie.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("data/prepared/pal_inputs"),
        help="Directory to write synthesized input JSONL files.",
    )
    parser.add_argument(
        "--n-records",
        type=int,
        default=100,
        help="Number of Meddies records to stream and adapt.",
    )
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--hf-split", type=str, default="train")
    parser.add_argument(
        "--llm",
        action="store_true",
        help=(
            "Use NVIDIA NIM LLM (openai/gpt-oss-120b by default) to generate"
            " dialogue / chosen / rejected text. Falls back to rule-based if no"
            " API key is present."
        ),
    )
    parser.add_argument(
        "--llm-model",
        type=str,
        default=None,
        help="Override the NIM model id (e.g. 'z-ai/glm-5.1'). Implies --llm.",
    )
    args = parser.parse_args(argv)

    llm_client: LlmCallable | None = None
    if args.llm or args.llm_model:
        llm_client = _build_llm_client_from_env(model=args.llm_model)

    report = run(
        args.out_dir,
        args.n_records,
        seed=args.seed,
        hf_split=args.hf_split,
        llm_client=llm_client,
    )
    print("[synthesizer] report:")
    for k, v in report.items():
        print(f"  {k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
