'''reprioritization_engine
Implements evidence-based reprioritization of acquisition and curation.
'''\n\nfrom __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom typing import List, Dict, Any\n\n# Placeholder imports – actual implementations to be added\n# from .evaluation_feedback import EvaluationFeedback\n# from .priority_queue import PriorityQueue\n\n@dataclass\nclass EvidenceItem:\n    """Simple representation of evaluation evidence impacting priority."""\n    source_id: str\n    evidence_type: str  # e.g., 'performance_gap', 'quality_issue'\n    score: float  # magnitude of impact, >0\n    details: Dict[str, Any]\n\n\nclass ReprioritizationEngine:\n    """Core engine to adjust priorities based on evidence.
\n    The engine receives a list of EvidenceItem objects and produces a
    deterministic ordering for acquisition/curation tasks. It is deliberately
    lightweight – heavy logic (LLM scoring, database access) lives in the
    surrounding services.\n    """\n\n    def __init__(self, base_priority: List[str] | None = None) -> None:\n        # base_priority is an ordered list of task identifiers (ids).\n        self.base_priority = base_priority or []\n        self.adjustments: Dict[str, float] = {}\n\n    def apply_evidence(self, evidence: List[EvidenceItem]) -> None:\n        """Accumulate score adjustments for each task based on evidence."""\n        for ev in evidence:\n            task_id = ev.details.get('task_id')\n            if not task_id:
                continue\n            # Simple linear impact – can be replaced with more complex logic\n            self.adjustments[task_id] = self.adjustments.get(task_id, 0.0) + ev.score\n\n    def reprioritize(self) -> List[str]:\n        """Return a new ordering of task ids.
\n        Tasks with higher accumulated adjustment move forward. Original order
        is preserved for ties.\n        """\n        # Combine base list with any new tasks discovered in adjustments\n        all_tasks = list(dict.fromkeys(self.base_priority + list(self.adjustments)))\n        # Sort by adjustment descending, then original index\n        def sort_key(tid: str):\n            # negative because higher scores should come first\n            return (-self.adjustments.get(tid, 0.0), self.base_priority.index(tid) if tid in self.base_priority else float('inf'))\n        return sorted(all_tasks, key=sort_key)\n\n    # Convenience method used by services\n    def compute_new_order(self, evidence: List[EvidenceItem]) -> List[str]:\n        self.apply_evidence(evidence)\n        return self.reprioritize()\n\n# Example stub usage (to be replaced by service integration)\nif __name__ == '__main__':\n    engine = ReprioritizationEngine(base_priority=['task_a', 'task_b', 'task_c'])\n    sample = [\n        EvidenceItem(source_id='eval1', evidence_type='performance_gap', score=2.5, details={'task_id': 'task_c'}),\n        EvidenceItem(source_id='eval2', evidence_type='quality_issue', score=1.0, details={'task_id': 'task_a'}),\n    ]\n    new_order = engine.compute_new_order(sample)\n    print('New priority order:', new_order)\n