version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
  - package-ecosystem: pip
    directory: /packages/data-designer-config
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore"
  - package-ecosystem: pip
    directory: /packages/data-designer-engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore"
  - package-ecosystem: pip
    directory: /packages/data-designer
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore"
