"""Asana MTGC progress synchronization for dataset assembly runs."""

from __future__ import annotations

import json
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol

from ai.pipelines.orchestrator.orchestration.asana_tracker_client import (
    AsanaTrackerClient,
)
from ai.pipelines.orchestrator.utils.logger import get_logger

logger = get_logger("dataset_pipeline.asana_progress_service")

TASK_KEY_PATTERN = re.compile(r"\bMTGC-\d{2}\b")


class AsanaProgressConfigProtocol(Protocol):
    enable_asana_sync: bool
    asana_project_gid: str | None
    asana_section_gid: str | None
    asana_parent_task_gid: str | None
    asana_task_gid_output_path: str
    asana_task_key_mapping_output_path: str
    asana_task_transition_output_path: str


class AsanaProgressStatsProtocol(Protocol):
    warnings: list[str]


class AsanaProgressSyncService:
    """Own Asana checklist task creation and MTGC transition updates."""

    def __init__(
        self,
        *,
        config: AsanaProgressConfigProtocol,
        stats: AsanaProgressStatsProtocol,
        asana_client: AsanaTrackerClient,
    ) -> None:
        self.config = config
        self.stats = stats
        self.asana_client = asana_client

    @staticmethod
    def _is_valid_gid(value: str | None) -> bool:
        return isinstance(value, str) and bool(re.fullmatch(r"\d+", value))

    @staticmethod
    def _extract_task_key(name: str | None) -> str | None:
        if not isinstance(name, str):
            return None
        match = TASK_KEY_PATTERN.search(name)
        if not match:
            return None
        return match.group(0)

    def sync_checklist_task(self, checklist: dict[str, Any], checklist_path: Path) -> None:
        """Create/update Asana checklist task and apply MTGC task transitions."""
        if not self.config.enable_asana_sync:
            return

        project_gid = self.config.asana_project_gid
        if not self._is_valid_gid(project_gid):
            self._warn("Asana sync skipped: ASANA_PROJECT_GID missing or invalid")
            return

        section_gid = self._validated_optional_gid(
            self.config.asana_section_gid,
            "Asana sync skipped section assignment: ASANA_SECTION_GID is invalid",
        )
        parent_gid = self._validated_optional_gid(
            self.config.asana_parent_task_gid,
            "Asana sync skipped parent linkage: ASANA_PARENT_TASK_GID is invalid",
        )

        timestamp = str(checklist.get("generated_at", datetime.now(timezone.utc).isoformat()))
        drift_ok = bool(checklist.get("stage_drift_within_tolerance", False))
        total_samples = checklist.get("total_samples", 0)

        # Extract dataset metadata
        dataset_info = checklist.get("dataset_info", {})
        dataset_size = dataset_info.get("size_bytes", 0)
        dataset_version = dataset_info.get("version", "unknown")
        data_quality_score = dataset_info.get("quality_score", 0.0)
        validation_passed = dataset_info.get("validation_passed", False)

        status_icon = "✅" if drift_ok else "⚠️"
        task_name = f"{status_icon} Training Checklist {timestamp}"

        notes_lines = [
            "Automated training checklist sync from dataset assembly workflow.",
            f"Generated at: {timestamp}",
            f"Total samples: {total_samples}",
            f"Dataset version: {dataset_version}",
            f"Dataset size: {dataset_size / (1024**2):.2f} MB",
            f"Data quality score: {data_quality_score:.2f}",
            f"Validation passed: {validation_passed}",
            f"Stage drift within tolerance: {drift_ok}",
            f"Checklist artifact: {checklist_path}",
        ]
        drift_failures = checklist.get("stage_drift_failures", [])
        if isinstance(drift_failures, list) and drift_failures:
            notes_lines.append("Stage drift failures: " + ", ".join(map(str, drift_failures)))

        task_payload: dict[str, Any] = {
            "name": task_name,
            "notes": "\n".join(notes_lines),
            "projects": [project_gid],
        }
        if section_gid:
            task_payload["memberships"] = [{"project": project_gid, "section": section_gid}]

        try:
            task_data = self._create_run_task(task_payload, parent_gid)
            run_task_gid = str(task_data.get("gid", "")).strip()
            if not self._is_valid_gid(run_task_gid):
                raise RuntimeError("Asana returned invalid task gid")

            self._create_stage_balance_subtasks(run_task_gid, checklist)
            self.asana_client.request(
                "POST",
                f"/tasks/{run_task_gid}/stories",
                {
                    "text": (
                        "Linked checklist generated by dataset assembly workflow.\n"
                        f"Artifact path: {checklist_path}"
                    )
                },
            )

            gid_path = Path(self.config.asana_task_gid_output_path)
            gid_path.parent.mkdir(parents=True, exist_ok=True)
            gid_path.write_text(run_task_gid, encoding="utf-8")

            self._sync_mtgc_task_transitions(checklist, str(project_gid))
        except Exception as exc:
            self._warn(f"Asana sync failed: {exc}")

    def _validated_optional_gid(self, gid: str | None, warning: str) -> str | None:
        if gid and not self._is_valid_gid(gid):
            self._warn(warning)
            return None
        return gid

    def _create_run_task(
        self, task_payload: dict[str, Any], parent_gid: str | None
    ) -> dict[str, Any]:
        if parent_gid:
            task_data = self.asana_client.request(
                "POST",
                f"/tasks/{parent_gid}/subtasks",
                task_payload,
            )
        else:
            task_data = self.asana_client.request("POST", "/tasks", task_payload)
        if not isinstance(task_data, dict):
            raise RuntimeError("Asana task creation returned invalid payload")
        return task_data

    def _create_stage_balance_subtasks(
        self, run_task_gid: str, checklist: dict[str, Any]
    ) -> None:
        stage_balance = checklist.get("report", {}).get("stage_balance", {})
        if not isinstance(stage_balance, dict):
            return
        for stage, metrics in stage_balance.items():
            if not isinstance(metrics, dict):
                continue
            actual = metrics.get("final_actual", metrics.get("actual", 0))
            drift = metrics.get("drift_vs_target", 0)
            subtask_name = f"{stage}: samples={actual}, drift={drift}"
            self.asana_client.request(
                "POST",
                f"/tasks/{run_task_gid}/subtasks",
                {"name": subtask_name},
            )

    def _load_task_key_gid_mapping(self, project_gid: str) -> dict[str, str]:
        mapping: dict[str, str] = {}
        mapping_path = Path(self.config.asana_task_key_mapping_output_path)

        if mapping_path.exists():
            try:
                existing = json.loads(mapping_path.read_text(encoding="utf-8"))
                if isinstance(existing, dict):
                    for task_key, gid in existing.items():
                        gid_str = str(gid)
                        if isinstance(task_key, str) and self._is_valid_gid(gid_str):
                            mapping[task_key] = gid_str
            except Exception as exc:
                self._warn(f"Failed to read task key mapping file: {exc}")

        try:
            tasks = self.asana_client.request(
                "GET",
                f"/projects/{project_gid}/tasks",
                payload=None,
                query_params={"limit": 100, "opt_fields": "gid,name"},
            )
            if isinstance(tasks, list):
                for task in tasks:
                    if not isinstance(task, dict):
                        continue
                    task_key = self._extract_task_key(task.get("name"))
                    gid = str(task.get("gid", "")).strip()
                    if task_key and self._is_valid_gid(gid):
                        mapping[task_key] = gid
        except Exception as exc:
            self._warn(f"Failed to resolve MTGC task keys from Asana project: {exc}")

        try:
            mapping_path.parent.mkdir(parents=True, exist_ok=True)
            mapping_path.write_text(json.dumps(mapping, indent=2), encoding="utf-8")
        except Exception as exc:
            self._warn(f"Failed to write task key mapping file: {exc}")

        return mapping

    def _derive_mtgc_status_targets(
        self, checklist: dict[str, Any], task_key_gid_map: dict[str, str]
    ) -> dict[str, dict[str, Any]]:
        split_counts = checklist.get("split_counts", {})
        split_aggregate = split_counts.get("aggregate") if isinstance(split_counts, dict) else None
        ops_freshness = checklist.get("ops_freshness", {})
        ops_all_fresh = bool(ops_freshness.get("all_fresh", False)) if isinstance(ops_freshness, dict) else False

        mapping_resolved = all(
            task_key in task_key_gid_map for task_key in ("MTGC-09", "MTGC-10", "MTGC-12")
        )

        signal_map: dict[str, dict[str, Any]] = {
            "asana_sync.authenticated": {
                "task_keys": ["MTGC-09"],
                "passed": self.asana_client.has_auth_context(),
            },
            "checklist_mapping.resolved": {
                "task_keys": ["MTGC-10"],
                "passed": mapping_resolved,
            },
            "ops_freshness.all_fresh": {
                "task_keys": ["MTGC-12"],
                "passed": ops_all_fresh,
            },
            "stage_drift_within_tolerance": {
                "task_keys": ["MTGC-01", "MTGC-08"],
                "passed": bool(checklist.get("stage_drift_within_tolerance", False)),
            },
            "split_counts.aggregate_present": {
                "task_keys": ["MTGC-06"],
                "passed": isinstance(split_aggregate, dict),
            },
        }

        targets: dict[str, dict[str, Any]] = {}
        for signal_key, signal in signal_map.items():
            task_keys = signal.get("task_keys", [])
            passed = bool(signal.get("passed", False))
            for task_key in task_keys:
                entry = targets.setdefault(task_key, {"passed": True, "signal_keys": []})
                entry["passed"] = bool(entry["passed"]) and passed
                entry["signal_keys"].append(signal_key)
        return targets

    def _sync_mtgc_task_transitions(self, checklist: dict[str, Any], project_gid: str) -> None:
        task_key_gid_map = self._load_task_key_gid_mapping(project_gid)
        targets = self._derive_mtgc_status_targets(checklist, task_key_gid_map)
        generated_at = str(checklist.get("generated_at", datetime.now(timezone.utc).isoformat()))

        transition_results: dict[str, Any] = {
            "generated_at": generated_at,
            "task_key_gid_map": task_key_gid_map,
            "targets": targets,
            "updates": {},
        }

        work_items: list[tuple[str, str, bool, list[str]]] = []
        for task_key, target in targets.items():
            gid = task_key_gid_map.get(task_key)
            if not self._is_valid_gid(gid):
                self._warn(f"Asana transition skipped for {task_key}: missing gid mapping")
                transition_results["updates"][task_key] = {
                    "updated": False,
                    "reason": "missing_gid_mapping",
                    "signals": target.get("signal_keys", []),
                }
                continue

            work_items.append(
                (
                    task_key,
                    str(gid),
                    bool(target.get("passed", False)),
                    list(target.get("signal_keys", [])),
                )
            )

        max_workers = min(8, max(1, len(work_items)))
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_map = {
                executor.submit(
                    self._apply_transition,
                    task_key,
                    gid,
                    should_complete,
                    signal_keys,
                    generated_at,
                ): task_key
                for task_key, gid, should_complete, signal_keys in work_items
            }
            for future in as_completed(future_map):
                task_key, update_payload, warning = future.result()
                transition_results["updates"][task_key] = update_payload
                if warning:
                    self._warn(warning)

        transition_path = Path(self.config.asana_task_transition_output_path)
        try:
            transition_path.parent.mkdir(parents=True, exist_ok=True)
            transition_path.write_text(
                json.dumps(transition_results, indent=2), encoding="utf-8"
            )
        except Exception as exc:
            self._warn(f"Failed to write Asana transition results: {exc}")

    def _apply_transition(
        self,
        task_key: str,
        gid: str,
        should_complete: bool,
        signal_keys: list[str],
        generated_at: str,
    ) -> tuple[str, dict[str, Any], str | None]:
        try:
            self.asana_client.request(
                "PUT",
                f"/tasks/{gid}",
                payload={"completed": should_complete},
            )
            self.asana_client.request(
                "POST",
                f"/tasks/{gid}/stories",
                payload={
                    "text": (
                        f"Checklist transition update ({generated_at}): "
                        f"completed={should_complete}; signals={', '.join(signal_keys)}"
                    )
                },
            )
            return (
                task_key,
                {
                    "updated": True,
                    "gid": gid,
                    "completed": should_complete,
                    "signals": signal_keys,
                },
                None,
            )
        except Exception as exc:
            return (
                task_key,
                {
                    "updated": False,
                    "gid": gid,
                    "completed": should_complete,
                    "signals": signal_keys,
                    "error": str(exc),
                },
                f"Asana transition failed for {task_key} ({gid}): {exc}",
            )

    def _warn(self, message: str) -> None:
        logger.warning(message)
        self.stats.warnings.append(message)


__all__ = ["AsanaProgressSyncService"]
